### ISSUE TITLE
Implement new methods on Collection class.

### ISSUE THREAD

**Issue by Theo-Nejm** [rest-models/rest-models#4]
- [x] Implement save method: can receive 1 optional id parameter. In this case, save the model that represents this id. Else, save all models in the collection.
- [x] Implement filter method: can fetch data based on filters passed inside a array of 2 position arrays (same as Object.entries()) with the filter and the value. Ex: [["isSubscribed", true], ["points", 10]]

**Comment by SampaioLeal** [comment]
Please see what is already implemented in #3 and update the tasks

**Comment by Theo-Nejm** [comment]
> Please see what is already implemented in #3 and update the tasks

Done. Two methods remained.
